#!/bin/sh -ev
# http://stackoverflow.com/a/14729121/430128
tmp_branch=__tmp_empty_root
git symbolic-ref HEAD refs/heads/$tmp_branch
git rm --cached -r . || true
git clean -f -d
touch -d '1970-01-01 UTC' .
GIT_COMMITTER_DATE='1970-01-01T00:00:00 +0000' git commit \
  --date='1970-01-01T00:00:00 +0000' --allow-empty -m 'Initial commit'
git rebase --committer-date-is-author-date --onto $tmp_branch --root master
git branch -d $tmp_branch
